import type {
  ActivityItem,
  CityHeat,
  CreatorDrop,
  FreeSignal,
  PulseMetrics,
  ScoreLabel,
  SignalCategory,
} from "./types";

export const CATEGORIES: {
  slug: SignalCategory | "near" | "live" | "today";
  label: string;
  href: string;
  blurb: string;
}[] = [
  { slug: "get", label: "GET FREE", href: "/get-free", blurb: "Samples, products, giveaways" },
  { slug: "go", label: "GO FREE", href: "/go-free", blurb: "Attractions, events, days out" },
  { slug: "eat", label: "EAT FREE", href: "/eat-free", blurb: "Food, drinks, tastings" },
  { slug: "learn", label: "LEARN FREE", href: "/learn-free", blurb: "Courses, books, skills" },
  { slug: "play", label: "PLAY FREE", href: "/play-free", blurb: "Games, sport, entertainment" },
  { slug: "try", label: "TRY FREE", href: "/try-free", blurb: "Software, gyms, streaming" },
  { slug: "kids", label: "KIDS FREE", href: "/kids-free", blurb: "Family & school holidays" },
  { slug: "online", label: "ONLINE FREE", href: "/online-free", blurb: "AI, tools, downloads" },
  { slug: "near", label: "NEAR ME", href: "/near-me", blurb: "Free within your radius" },
  { slug: "live", label: "LIVE", href: "/live", blurb: "Everything changing now" },
  { slug: "today", label: "TODAY", href: "/today", blurb: "Available right now" },
];

export const PULSE: PulseMetrics = {
  liveFreebies: 2483,
  valueAvailable: 87420,
  claimsToday: 18492,
  newToday: 347,
  endingSoon: 126,
  verifiedPct: 93,
  peopleWatching: 6491,
};

export const TICKER_ITEMS = [
  "LONDON ↑ 23%",
  "FREE FOOD 🔥",
  "17 NEW KIDS OFFERS",
  "MANCHESTER ↑ 18%",
  "3 NATIONAL FREEBIES JUST DROPPED",
  "BIRMINGHAM ↑ 11%",
  "FREE COFFEE SURGE",
  "82 CREATOR DROPS LIVE",
  "NO-CARD TRIALS ↑ 9%",
];

export const CITY_HEAT: CityHeat[] = [
  { city: "London", level: 10, label: "HOT", newSignals: 83 },
  { city: "Manchester", level: 8, label: "HOT", newSignals: 41 },
  { city: "Birmingham", level: 6, label: "WARM", newSignals: 27 },
  { city: "Liverpool", level: 5, label: "WARM", newSignals: 19 },
  { city: "Leeds", level: 4, label: "STEADY", newSignals: 14 },
  { city: "Bristol", level: 3, label: "STEADY", newSignals: 11 },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a1", text: "Someone in London just got £18 FREE", minsAgo: 0 },
  { id: "a2", text: "23 people claimed Free Coffee", minsAgo: 1 },
  { id: "a3", text: "Manchester member found a new signal", minsAgo: 2 },
  { id: "a4", text: "Free Family Day Out crossed 500 claims", minsAgo: 3 },
  { id: "a5", text: "£79 software offer just became FREE", minsAgo: 4 },
  { id: "a6", text: "Creator Drop: skincare set — 12 spots left", minsAgo: 5 },
  { id: "a7", text: "Birmingham free exhibition verified", minsAgo: 6 },
  { id: "a8", text: "No-card AI trial hit 97% success rate", minsAgo: 8 },
];

export const SIGNALS: FreeSignal[] = [
  {
    id: "sig-coffee-london",
    title: "Free Coffee — First 100",
    summary: "Independent café giving free flat whites to the first 100 customers this morning.",
    category: "eat",
    subcategory: "Drinks",
    location: "Bromley High Street",
    country: "GB",
    distanceMiles: 0.8,
    freeScore: 94,
    normalValue: 3.8,
    claims: 143,
    watching: 217,
    remaining: 72,
    successRate: 96,
    verifiedMinsAgo: 7,
    requiresCard: false,
    cancelReminder: false,
    verification: "exclusive",
    status: "live",
    activityDelta: 34,
    city: "London",
    workedFor: 1342,
    didntWork: 41,
    updates: [
      { time: "18:32", text: "Member confirmed offer working" },
      { time: "18:21", text: "14 new claims" },
      { time: "18:04", text: "Availability changed — 72 remaining" },
      { time: "17:46", text: "Offer verified" },
    ],
    tags: ["No card", "Near you", "Food"],
  },
  {
    id: "sig-spotify",
    title: "Spotify Premium — 30 Day Trial",
    summary: "Full Premium access for 30 days. Cancel reminder available before billing starts.",
    category: "try",
    subcategory: "Streaming",
    location: "Nationwide",
    country: "GB",
    freeScore: 91,
    normalValue: 11.99,
    claims: 2481,
    watching: 604,
    successRate: 97,
    verifiedMinsAgo: 11,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 3,
    city: "UK",
    workedFor: 2104,
    didntWork: 68,
    updates: [
      { time: "19:01", text: "51 people already in" },
      { time: "18:58", text: "Signal just dropped" },
      { time: "18:55", text: "Verified by ZeroSpenders" },
    ],
    tags: ["Trial", "Cancel reminder", "Entertainment"],
  },
  {
    id: "sig-family-tickets",
    title: "Free Family Attraction Tickets",
    summary: "Family of four entry to a major attraction. Limited inventory — ending fast.",
    category: "kids",
    subcategory: "Attractions",
    location: "London",
    country: "GB",
    distanceMiles: 4.3,
    freeScore: 88,
    normalValue: 72,
    claims: 327,
    watching: 327,
    remaining: 18,
    successRate: 91,
    verifiedMinsAgo: 22,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 1.7,
    city: "London",
    workedFor: 289,
    didntWork: 28,
    updates: [
      { time: "17:12", text: "Only 18 left" },
      { time: "16:40", text: "327 watching" },
      { time: "15:05", text: "Community confirmed working" },
    ],
    tags: ["Kids", "Ending soon", "High value"],
  },
  {
    id: "sig-museum",
    title: "Natural History Museum — Free Entry",
    summary: "Permanent collections always free. Timed entry recommended at weekends.",
    category: "go",
    subcategory: "Museums",
    location: "South Kensington",
    country: "GB",
    distanceMiles: 2.1,
    freeScore: 86,
    normalValue: 0,
    claims: 1206,
    watching: 188,
    successRate: 99,
    verifiedMinsAgo: 4,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "London",
    workedFor: 1180,
    didntWork: 9,
    updates: [
      { time: "19:10", text: "Last verified 4 mins ago" },
      { time: "12:00", text: "Weekend queues expected" },
    ],
    tags: ["Always free", "Family", "Culture"],
  },
  {
    id: "sig-skincare",
    title: "Premium Skincare Sample Set",
    summary: "Brand sample pack by post. No purchase necessary. Limited to UK addresses.",
    category: "get",
    subcategory: "Beauty",
    location: "UK delivery",
    country: "GB",
    freeScore: 82,
    normalValue: 28,
    claims: 894,
    watching: 412,
    remaining: 210,
    successRate: 88,
    verifiedMinsAgo: 35,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "UK",
    workedFor: 712,
    didntWork: 96,
    updates: [
      { time: "16:20", text: "Community signal upgraded after 40 confirms" },
      { time: "14:02", text: "210 packs remaining" },
    ],
    tags: ["Samples", "Beauty", "No purchase"],
    sponsored: true,
  },
  {
    id: "sig-coding",
    title: "Free Intro to Coding Certificate",
    summary: "Self-paced online course with a free certificate on completion.",
    category: "learn",
    subcategory: "Courses",
    location: "Online",
    country: "GLOBAL",
    freeScore: 79,
    normalValue: 49,
    claims: 1560,
    watching: 290,
    successRate: 94,
    verifiedMinsAgo: 60,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Online",
    workedFor: 1402,
    didntWork: 88,
    updates: [
      { time: "10:00", text: "Verified working" },
      { time: "09:12", text: "Certificate download confirmed" },
    ],
    tags: ["Courses", "Certificate", "No card"],
  },
  {
    id: "sig-game",
    title: "PC Game Giveaway Weekend",
    summary: "Full game unlock for a limited weekend window. Claim before Monday.",
    category: "play",
    subcategory: "Games",
    location: "Online",
    country: "GLOBAL",
    freeScore: 84,
    normalValue: 24.99,
    claims: 4320,
    watching: 980,
    remaining: 0,
    successRate: 92,
    verifiedMinsAgo: 15,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 36,
    city: "Online",
    workedFor: 3901,
    didntWork: 310,
    updates: [
      { time: "18:00", text: "Still reclaimable" },
      { time: "08:00", text: "Weekend window opened" },
    ],
    tags: ["Games", "Limited time"],
  },
  {
    id: "sig-ai",
    title: "AI Writing Suite — No Card Trial",
    summary: "14-day full access. No credit card required to start.",
    category: "online",
    subcategory: "AI Tools",
    location: "Online",
    country: "GLOBAL",
    freeScore: 90,
    normalValue: 29,
    claims: 1104,
    watching: 501,
    successRate: 95,
    verifiedMinsAgo: 9,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 18,
    city: "Online",
    workedFor: 998,
    didntWork: 42,
    updates: [
      { time: "19:05", text: "No card confirmed" },
      { time: "18:47", text: "Signal detected" },
    ],
    tags: ["AI", "No card", "Tools"],
  },
  {
    id: "sig-yoga",
    title: "Outdoor Yoga — Free Community Class",
    summary: "Saturday morning park class. Mats provided for the first 40 arrivals.",
    category: "go",
    subcategory: "Exercise",
    location: "Hyde Park",
    country: "GB",
    distanceMiles: 1.4,
    freeScore: 77,
    normalValue: 15,
    claims: 86,
    watching: 64,
    remaining: 40,
    successRate: 93,
    verifiedMinsAgo: 120,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "London",
    workedFor: 71,
    didntWork: 5,
    updates: [
      { time: "Yesterday", text: "Reported by community member" },
    ],
    tags: ["Exercise", "Weekend", "Near you"],
  },
  {
    id: "sig-birthday",
    title: "Birthday Free Dessert",
    summary: "Free dessert with any main on your birthday month. App signup required.",
    category: "eat",
    subcategory: "Birthday",
    location: "Nationwide",
    country: "GB",
    freeScore: 71,
    normalValue: 6.5,
    claims: 2201,
    watching: 155,
    successRate: 89,
    verifiedMinsAgo: 200,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "UK",
    workedFor: 1890,
    didntWork: 210,
    updates: [
      { time: "Mon", text: "Verified across 40 locations" },
    ],
    tags: ["Birthday", "Food"],
  },
  {
    id: "sig-kids-softplay",
    title: "Kids Soft Play — Free Taster",
    summary: "One free hour for under-8s this weekend. Book slot online.",
    category: "kids",
    subcategory: "Activities",
    location: "Manchester",
    country: "GB",
    distanceMiles: 3.2,
    freeScore: 85,
    normalValue: 12,
    claims: 194,
    watching: 122,
    remaining: 55,
    successRate: 90,
    verifiedMinsAgo: 40,
    requiresCard: false,
    cancelReminder: false,
    verification: "exclusive",
    status: "new",
    droppedMinsAgo: 55,
    city: "Manchester",
    workedFor: 160,
    didntWork: 18,
    updates: [
      { time: "17:30", text: "Exclusive business listing" },
      { time: "17:00", text: "Weekend slots opened" },
    ],
    tags: ["Kids", "Weekend", "Exclusive"],
  },
  {
    id: "sig-gym",
    title: "Gym — Free Week Pass",
    summary: "Full club access for 7 days. No contract. Card held but not charged if cancelled.",
    category: "try",
    subcategory: "Gyms",
    location: "Multiple cities",
    country: "GB",
    freeScore: 76,
    normalValue: 35,
    claims: 670,
    watching: 240,
    successRate: 86,
    verifiedMinsAgo: 80,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "live",
    city: "UK",
    workedFor: 540,
    didntWork: 88,
    updates: [
      { time: "Noon", text: "Cancel reminder enabled" },
    ],
    tags: ["Gym", "Trial", "Cancel reminder"],
  },
  // —— USA ——
  {
    id: "sig-us-birthday-dessert",
    title: "Birthday Free Dessert",
    summary: "Sign up once and claim a free dessert (or entrée) on your birthday at major US chains.",
    category: "eat",
    subcategory: "Birthday",
    location: "Nationwide",
    country: "US",
    freeScore: 92,
    normalValue: 12,
    claims: 8420,
    watching: 1204,
    successRate: 95,
    verifiedMinsAgo: 18,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "USA",
    workedFor: 7910,
    didntWork: 210,
    updates: [
      { time: "14:02", text: "Working at 40+ chains this week" },
      { time: "09:11", text: "Community re-verified" },
    ],
    tags: ["Birthday", "No card", "Food"],
  },
  {
    id: "sig-us-beauty-samples",
    title: "Free Beauty Sample Pack",
    summary: "Brand sample kit with paid shipping waived on promo codes — beauty freebies dropping daily.",
    category: "get",
    subcategory: "Beauty",
    location: "US delivery",
    country: "US",
    freeScore: 87,
    normalValue: 28,
    claims: 3102,
    watching: 890,
    remaining: 140,
    successRate: 89,
    verifiedMinsAgo: 26,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "new",
    droppedMinsAgo: 12,
    city: "USA",
    workedFor: 2680,
    didntWork: 190,
    updates: [
      { time: "15:40", text: "140 kits left in this drop" },
    ],
    tags: ["Samples", "Beauty", "Just dropped"],
  },
  {
    id: "sig-us-streaming-trial",
    title: "Streaming — Free Month Trial",
    summary: "Full catalogue for 30 days. Card required — cancel reminder included before billing.",
    category: "try",
    subcategory: "Streaming",
    location: "Nationwide",
    country: "US",
    freeScore: 90,
    normalValue: 15.99,
    claims: 5210,
    watching: 980,
    successRate: 96,
    verifiedMinsAgo: 9,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "live",
    city: "USA",
    workedFor: 4990,
    didntWork: 120,
    updates: [
      { time: "16:20", text: "Cancel reminder armed for members" },
    ],
    tags: ["Trial", "Cancel reminder", "Entertainment"],
  },
  {
    id: "sig-us-museum-free",
    title: "Smithsonian Museums — Free Entry",
    summary: "National museums in Washington, D.C. — permanent collections free year-round.",
    category: "go",
    subcategory: "Museums",
    location: "Washington, D.C.",
    country: "US",
    distanceMiles: 2.4,
    freeScore: 94,
    normalValue: 0,
    claims: 2204,
    watching: 410,
    successRate: 99,
    verifiedMinsAgo: 5,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Washington",
    workedFor: 2188,
    didntWork: 6,
    updates: [
      { time: "11:00", text: "Security lines normal for weekday" },
    ],
    tags: ["Museums", "No card", "High value"],
  },
  // —— Canada ——
  {
    id: "sig-ca-tims-reward",
    title: "Free Hot Drink Reward",
    summary: "Loyalty app drop — free medium hot drink after signup + first scan in-store.",
    category: "eat",
    subcategory: "Drinks",
    location: "Nationwide",
    country: "CA",
    freeScore: 88,
    normalValue: 3.5,
    claims: 1980,
    watching: 620,
    successRate: 93,
    verifiedMinsAgo: 14,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    activityDelta: 22,
    city: "Canada",
    workedFor: 1810,
    didntWork: 55,
    updates: [
      { time: "10:18", text: "Verified in Toronto & Vancouver" },
    ],
    tags: ["Coffee", "App", "No card"],
  },
  {
    id: "sig-ca-sample-box",
    title: "Canadian Free Sample Box",
    summary: "Grocery and household samples shipped free within Canada this week only.",
    category: "get",
    subcategory: "Samples",
    location: "Canada delivery",
    country: "CA",
    freeScore: 84,
    normalValue: 22,
    claims: 940,
    watching: 401,
    remaining: 85,
    successRate: 88,
    verifiedMinsAgo: 33,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "ending",
    endsInHours: 2.5,
    city: "Canada",
    workedFor: 820,
    didntWork: 70,
    updates: [
      { time: "13:05", text: "85 boxes remaining" },
    ],
    tags: ["Samples", "Ending soon"],
  },
  {
    id: "sig-ca-park-free",
    title: "National Parks — Free Discovery Day",
    summary: "Free entry to Parks Canada sites on the next Discovery Day window.",
    category: "go",
    subcategory: "Parks",
    location: "Nationwide parks",
    country: "CA",
    freeScore: 91,
    normalValue: 20,
    claims: 1560,
    watching: 720,
    successRate: 97,
    verifiedMinsAgo: 40,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 25,
    city: "Canada",
    workedFor: 1490,
    didntWork: 18,
    updates: [
      { time: "08:00", text: "Dates confirmed for this season" },
    ],
    tags: ["Parks", "Family", "Just dropped"],
  },
  // —— Australia ——
  {
    id: "sig-au-woolies-sample",
    title: "Supermarket Free Taste Session",
    summary: "In-store tasting sessions — free snacks and drink samples this weekend.",
    category: "eat",
    subcategory: "Tastings",
    location: "Major metros",
    country: "AU",
    freeScore: 82,
    normalValue: 8,
    claims: 760,
    watching: 290,
    successRate: 90,
    verifiedMinsAgo: 21,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "Sydney",
    workedFor: 690,
    didntWork: 40,
    updates: [
      { time: "12:40", text: "Sydney & Melbourne confirmed" },
    ],
    tags: ["Tasting", "Weekend", "No card"],
  },
  {
    id: "sig-au-beauty-kit",
    title: "AU Beauty Freebie Drop",
    summary: "Australian brand sample kit — free with community code, shipping included.",
    category: "get",
    subcategory: "Beauty",
    location: "AU delivery",
    country: "AU",
    freeScore: 86,
    normalValue: 35,
    claims: 1120,
    watching: 510,
    remaining: 60,
    successRate: 87,
    verifiedMinsAgo: 16,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 3.2,
    city: "Australia",
    workedFor: 980,
    didntWork: 65,
    updates: [
      { time: "17:10", text: "60 kits left" },
    ],
    tags: ["Beauty", "Samples", "Ending soon"],
  },
  {
    id: "sig-au-gallery-free",
    title: "State Gallery — Free Entry",
    summary: "Permanent collections free; timed tickets optional on busy days.",
    category: "go",
    subcategory: "Galleries",
    location: "Melbourne",
    country: "AU",
    distanceMiles: 1.2,
    freeScore: 89,
    normalValue: 0,
    claims: 1340,
    watching: 210,
    successRate: 99,
    verifiedMinsAgo: 8,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Melbourne",
    workedFor: 1320,
    didntWork: 5,
    updates: [
      { time: "10:05", text: "Quiet midweek visit window" },
    ],
    tags: ["Culture", "No card"],
  },
  // —— Ireland ——
  {
    id: "sig-ie-museum-free",
    title: "National Museums — Free Entry",
    summary: "Core national museum sites in Dublin free for all visitors.",
    category: "go",
    subcategory: "Museums",
    location: "Dublin",
    country: "IE",
    distanceMiles: 1.5,
    freeScore: 90,
    normalValue: 0,
    claims: 980,
    watching: 160,
    successRate: 99,
    verifiedMinsAgo: 11,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Dublin",
    workedFor: 970,
    didntWork: 4,
    updates: [
      { time: "09:30", text: "Verified open today" },
    ],
    tags: ["Museums", "Dublin", "No card"],
  },
  {
    id: "sig-ie-coffee-app",
    title: "Free Coffee App Drop",
    summary: "Irish café chain app giving a free regular coffee to new members this week.",
    category: "eat",
    subcategory: "Drinks",
    location: "Nationwide",
    country: "IE",
    freeScore: 85,
    normalValue: 3.6,
    claims: 540,
    watching: 210,
    successRate: 92,
    verifiedMinsAgo: 19,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "new",
    droppedMinsAgo: 40,
    city: "Ireland",
    workedFor: 500,
    didntWork: 22,
    updates: [
      { time: "15:00", text: "Working Cork & Dublin" },
    ],
    tags: ["Coffee", "App", "Just dropped"],
  },
  // —— New Zealand ——
  {
    id: "sig-nz-sample-pack",
    title: "NZ Free Sample Pack",
    summary: "Household and grocery samples shipping free within New Zealand.",
    category: "get",
    subcategory: "Samples",
    location: "NZ delivery",
    country: "NZ",
    freeScore: 83,
    normalValue: 20,
    claims: 410,
    watching: 180,
    remaining: 95,
    successRate: 88,
    verifiedMinsAgo: 28,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "New Zealand",
    workedFor: 360,
    didntWork: 28,
    updates: [
      { time: "11:20", text: "Auckland delivery confirmed" },
    ],
    tags: ["Samples", "Delivery"],
  },
  {
    id: "sig-nz-park-day",
    title: "DOC Day Pass — Free Weekend",
    summary: "Selected conservation sites waiving day fees this weekend.",
    category: "go",
    subcategory: "Outdoors",
    location: "Selected parks",
    country: "NZ",
    freeScore: 87,
    normalValue: 15,
    claims: 620,
    watching: 250,
    successRate: 94,
    verifiedMinsAgo: 35,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "New Zealand",
    workedFor: 590,
    didntWork: 15,
    updates: [
      { time: "07:45", text: "Weekend window live" },
    ],
    tags: ["Outdoors", "Weekend"],
  },
  // —— Germany ——
  {
    id: "sig-de-proben",
    title: "Gratis Produktprobe Pack",
    summary: "German sample portals dropping free product probes — beauty & household this week.",
    category: "get",
    subcategory: "Samples",
    location: "DE delivery",
    country: "DE",
    freeScore: 88,
    normalValue: 24,
    claims: 2210,
    watching: 760,
    remaining: 200,
    successRate: 90,
    verifiedMinsAgo: 12,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    activityDelta: 18,
    city: "Germany",
    workedFor: 2040,
    didntWork: 95,
    updates: [
      { time: "16:00", text: "New probe batch verified" },
    ],
    tags: ["Proben", "Samples", "No card"],
  },
  {
    id: "sig-de-museum",
    title: "Museum Free Sunday",
    summary: "Selected Berlin museums open free on the first Sunday — timed booking advised.",
    category: "go",
    subcategory: "Museums",
    location: "Berlin",
    country: "DE",
    distanceMiles: 2.0,
    freeScore: 86,
    normalValue: 14,
    claims: 880,
    watching: 340,
    successRate: 93,
    verifiedMinsAgo: 50,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 60,
    city: "Berlin",
    workedFor: 840,
    didntWork: 20,
    updates: [
      { time: "08:10", text: "Next free Sunday listed" },
    ],
    tags: ["Berlin", "Culture"],
  },
  // —— France ——
  {
    id: "sig-fr-echantillon",
    title: "Échantillons Beauté Gratuits",
    summary: "French beauty sample drops — free échantillons with community codes.",
    category: "get",
    subcategory: "Beauty",
    location: "FR delivery",
    country: "FR",
    freeScore: 85,
    normalValue: 26,
    claims: 1670,
    watching: 540,
    remaining: 110,
    successRate: 88,
    verifiedMinsAgo: 22,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "France",
    workedFor: 1490,
    didntWork: 80,
    updates: [
      { time: "14:30", text: "Paris & Lyon shipping live" },
    ],
    tags: ["Échantillons", "Beauty"],
  },
  {
    id: "sig-fr-museum-night",
    title: "Nuit des Musées — Free Entry",
    summary: "Special museum night — free evening entry across participating venues.",
    category: "go",
    subcategory: "Museums",
    location: "Multiple cities",
    country: "FR",
    freeScore: 91,
    normalValue: 16,
    claims: 2400,
    watching: 900,
    successRate: 96,
    verifiedMinsAgo: 70,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 5,
    city: "France",
    workedFor: 2280,
    didntWork: 40,
    updates: [
      { time: "19:00", text: "Queues building — arrive early" },
    ],
    tags: ["Culture", "Evening", "Ending soon"],
  },
  // —— Netherlands ——
  {
    id: "sig-nl-samples",
    title: "Gratis Samples Box",
    summary: "Dutch sample programmes shipping free household and beauty trials.",
    category: "get",
    subcategory: "Samples",
    location: "NL delivery",
    country: "NL",
    freeScore: 84,
    normalValue: 21,
    claims: 990,
    watching: 360,
    remaining: 130,
    successRate: 89,
    verifiedMinsAgo: 30,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "Netherlands",
    workedFor: 900,
    didntWork: 45,
    updates: [
      { time: "12:15", text: "Amsterdam delivery confirmed" },
    ],
    tags: ["Samples", "Gratis"],
  },
  // —— India ——
  {
    id: "sig-in-app-trial",
    title: "Premium App — Free Trial Week",
    summary: "Learning and productivity apps offering 7-day full access — no charge if cancelled.",
    category: "try",
    subcategory: "Apps",
    location: "Online",
    country: "IN",
    freeScore: 86,
    normalValue: 9,
    claims: 4200,
    watching: 1100,
    successRate: 94,
    verifiedMinsAgo: 10,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "live",
    city: "India",
    workedFor: 4010,
    didntWork: 95,
    updates: [
      { time: "18:40", text: "Cancel reminder available" },
    ],
    tags: ["Trial", "Apps", "Cancel reminder"],
  },
  {
    id: "sig-in-food-sample",
    title: "Free Snack Sample Drop",
    summary: "FMCG brands sending free snack samples via partner apps this week.",
    category: "get",
    subcategory: "Food samples",
    location: "Major cities",
    country: "IN",
    freeScore: 80,
    normalValue: 6,
    claims: 3100,
    watching: 840,
    remaining: 400,
    successRate: 85,
    verifiedMinsAgo: 24,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "new",
    droppedMinsAgo: 8,
    city: "India",
    workedFor: 2750,
    didntWork: 180,
    updates: [
      { time: "17:55", text: "Delhi & Mumbai stock live" },
    ],
    tags: ["Samples", "Food", "Just dropped"],
  },
  // —— Singapore ——
  {
    id: "sig-sg-museum",
    title: "National Museums — Free Entry Days",
    summary: "Selected Singapore museums free on designated citizen/PR or promo days.",
    category: "go",
    subcategory: "Museums",
    location: "Singapore",
    country: "SG",
    distanceMiles: 1.0,
    freeScore: 88,
    normalValue: 20,
    claims: 720,
    watching: 260,
    successRate: 95,
    verifiedMinsAgo: 45,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Singapore",
    workedFor: 690,
    didntWork: 12,
    updates: [
      { time: "09:00", text: "Next free window published" },
    ],
    tags: ["Culture", "Singapore"],
  },
  {
    id: "sig-sg-beauty-trial",
    title: "Beauty Counter Free Mini",
    summary: "Mall beauty counters giving free mini kits with skin consult — no purchase required.",
    category: "get",
    subcategory: "Beauty",
    location: "Orchard / malls",
    country: "SG",
    freeScore: 81,
    normalValue: 18,
    claims: 510,
    watching: 190,
    successRate: 86,
    verifiedMinsAgo: 38,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "Singapore",
    workedFor: 450,
    didntWork: 35,
    updates: [
      { time: "13:20", text: "Weekend slots filling" },
    ],
    tags: ["Beauty", "In-store"],
  },
  // —— South Africa ——
  {
    id: "sig-za-sample",
    title: "SA Free Sample Bundle",
    summary: "South African freebie sites listing grocery and personal care samples this week.",
    category: "get",
    subcategory: "Samples",
    location: "ZA delivery",
    country: "ZA",
    freeScore: 79,
    normalValue: 15,
    claims: 640,
    watching: 220,
    remaining: 150,
    successRate: 84,
    verifiedMinsAgo: 55,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "South Africa",
    workedFor: 560,
    didntWork: 48,
    updates: [
      { time: "11:40", text: "Johannesburg & Cape Town live" },
    ],
    tags: ["Samples", "Delivery"],
  },
  // —— Brazil ——
  {
    id: "sig-br-amostra",
    title: "Amostras Grátis — Beauty",
    summary: "Brazilian beauty brands releasing free amostras via partner portals.",
    category: "get",
    subcategory: "Beauty",
    location: "BR delivery",
    country: "BR",
    freeScore: 82,
    normalValue: 19,
    claims: 1880,
    watching: 640,
    remaining: 220,
    successRate: 86,
    verifiedMinsAgo: 27,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "new",
    droppedMinsAgo: 20,
    city: "Brazil",
    workedFor: 1650,
    didntWork: 110,
    updates: [
      { time: "15:10", text: "São Paulo fulfilment active" },
    ],
    tags: ["Amostras", "Beauty", "Just dropped"],
  },
  // —— Japan ——
  {
    id: "sig-jp-sample",
    title: "Free Japanese Sample Set",
    summary: "Brand sample programmes (試供品) — beauty and food samples with local signup.",
    category: "get",
    subcategory: "Samples",
    location: "JP delivery",
    country: "JP",
    freeScore: 87,
    normalValue: 25,
    claims: 2050,
    watching: 710,
    remaining: 180,
    successRate: 91,
    verifiedMinsAgo: 17,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Japan",
    workedFor: 1920,
    didntWork: 60,
    updates: [
      { time: "10:50", text: "Tokyo & Osaka shipping" },
    ],
    tags: ["試供品", "Samples"],
  },
  {
    id: "sig-jp-museum",
    title: "Museum Free Admission Day",
    summary: "Participating museums offering free admission on designated national days.",
    category: "go",
    subcategory: "Museums",
    location: "Major cities",
    country: "JP",
    freeScore: 85,
    normalValue: 12,
    claims: 980,
    watching: 300,
    successRate: 94,
    verifiedMinsAgo: 60,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Japan",
    workedFor: 940,
    didntWork: 18,
    updates: [
      { time: "08:20", text: "Next free day listed" },
    ],
    tags: ["Culture", "Free day"],
  },
  // —— Mexico ——
  {
    id: "sig-mx-muestra",
    title: "Muestras Gratis — Hogar",
    summary: "Mexican freebie portals listing household and personal care muestras this week.",
    category: "get",
    subcategory: "Samples",
    location: "MX delivery",
    country: "MX",
    freeScore: 80,
    normalValue: 14,
    claims: 870,
    watching: 310,
    remaining: 160,
    successRate: 85,
    verifiedMinsAgo: 42,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "Mexico",
    workedFor: 760,
    didntWork: 55,
    updates: [
      { time: "12:00", text: "CDMX delivery confirmed" },
    ],
    tags: ["Muestras", "Samples"],
  },
];

export const CREATOR_DROPS: CreatorDrop[] = [
  {
    id: "drop-skincare",
    title: "Premium Skincare Set",
    brand: "Lumina Skin",
    retailValue: 85,
    available: 100,
    applied: 47,
    selected: 23,
    closesInHours: 18,
    matchScore: 94,
    requirements: ["Instagram / TikTok", "Beauty audience", "UK", "1,000+ followers"],
    missionType: "TRY & TELL",
    category: "Beauty",
  },
  {
    id: "drop-dinner",
    title: "Free Dinner for Two",
    brand: "Borough Kitchen",
    retailValue: 75,
    available: 12,
    applied: 31,
    selected: 4,
    closesInHours: 48,
    matchScore: 88,
    requirements: ["1 Reel + 3 Stories", "Food audience", "London"],
    missionType: "LOCAL CREATOR MISSION",
    category: "Food",
  },
  {
    id: "drop-energy",
    title: "New Energy Drink Pack",
    brand: "Volt Run",
    retailValue: 18,
    available: 500,
    applied: 126,
    selected: 80,
    closesInHours: 72,
    matchScore: 81,
    requirements: ["Fitness / running interest", "TikTok or Instagram", "UGC welcome"],
    missionType: "TRY & TELL",
    category: "Fitness",
  },
];

export function scoreLabel(score: number): ScoreLabel {
  if (score >= 85) return "EXCEPTIONAL FREEBIE";
  if (score >= 65) return "GOOD SIGNAL";
  return "LOW CONFIDENCE";
}

export function formatGBP(n: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    maximumFractionDigits: n % 1 === 0 ? 0 : 2,
  }).format(n);
}

export function getSignal(id: string) {
  return SIGNALS.find((s) => s.id === id);
}

export function signalsByCategory(category: SignalCategory) {
  return SIGNALS.filter((s) => s.category === category);
}

export function trendingSignals() {
  return [...SIGNALS].sort((a, b) => (b.activityDelta ?? b.claims) - (a.activityDelta ?? a.claims)).slice(0, 5);
}

export function justDroppedSignals() {
  return SIGNALS.filter((s) => s.status === "new" || (s.droppedMinsAgo ?? 999) < 60)
    .sort((a, b) => (a.droppedMinsAgo ?? 999) - (b.droppedMinsAgo ?? 999))
    .slice(0, 5);
}

export function endingSoonSignals() {
  return SIGNALS.filter((s) => s.status === "ending" || (s.remaining !== undefined && s.remaining < 30))
    .sort((a, b) => (a.endsInHours ?? 99) - (b.endsInHours ?? 99))
    .slice(0, 5);
}

export function nearYouSignals() {
  return SIGNALS.filter((s) => s.distanceMiles !== undefined).sort(
    (a, b) => (a.distanceMiles ?? 99) - (b.distanceMiles ?? 99)
  );
}
