import type {
  ActivityItem,
  CityHeat,
  CreatorDrop,
  FreeSignal,
  PulseMetrics,
  ScoreLabel,
  SignalCategory,
} from "./types";

export const CATEGORIES: {
  slug: SignalCategory | "near" | "live" | "today";
  label: string;
  href: string;
  blurb: string;
}[] = [
  { slug: "get", label: "GET FREE", href: "/get-free", blurb: "Samples, products, giveaways" },
  { slug: "go", label: "GO FREE", href: "/go-free", blurb: "Attractions, events, days out" },
  { slug: "eat", label: "EAT FREE", href: "/eat-free", blurb: "Food, drinks, tastings" },
  { slug: "learn", label: "LEARN FREE", href: "/learn-free", blurb: "Courses, books, skills" },
  { slug: "play", label: "PLAY FREE", href: "/play-free", blurb: "Games, sport, entertainment" },
  { slug: "try", label: "TRY FREE", href: "/try-free", blurb: "Software, gyms, streaming" },
  { slug: "kids", label: "KIDS FREE", href: "/kids-free", blurb: "Family & school holidays" },
  { slug: "online", label: "ONLINE FREE", href: "/online-free", blurb: "AI, tools, downloads" },
  { slug: "near", label: "NEAR ME", href: "/near-me", blurb: "Free within your radius" },
  { slug: "live", label: "LIVE", href: "/live", blurb: "Everything changing now" },
  { slug: "today", label: "TODAY", href: "/today", blurb: "Available right now" },
];

export const PULSE: PulseMetrics = {
  liveFreebies: 2483,
  valueAvailable: 87420,
  claimsToday: 18492,
  newToday: 347,
  endingSoon: 126,
  verifiedPct: 93,
  peopleWatching: 6491,
};

export const TICKER_ITEMS = [
  "LONDON ↑ 23%",
  "FREE FOOD 🔥",
  "17 NEW KIDS OFFERS",
  "MANCHESTER ↑ 18%",
  "3 NATIONAL FREEBIES JUST DROPPED",
  "BIRMINGHAM ↑ 11%",
  "FREE COFFEE SURGE",
  "82 CREATOR DROPS LIVE",
  "NO-CARD TRIALS ↑ 9%",
];

export const CITY_HEAT: CityHeat[] = [
  { city: "London", level: 10, label: "HOT", newSignals: 83 },
  { city: "Manchester", level: 8, label: "HOT", newSignals: 41 },
  { city: "Birmingham", level: 6, label: "WARM", newSignals: 27 },
  { city: "Liverpool", level: 5, label: "WARM", newSignals: 19 },
  { city: "Leeds", level: 4, label: "STEADY", newSignals: 14 },
  { city: "Bristol", level: 3, label: "STEADY", newSignals: 11 },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a1", text: "Someone in London just got £18 FREE", minsAgo: 0 },
  { id: "a2", text: "23 people claimed Free Coffee", minsAgo: 1 },
  { id: "a3", text: "Manchester member found a new signal", minsAgo: 2 },
  { id: "a4", text: "Free Family Day Out crossed 500 claims", minsAgo: 3 },
  { id: "a5", text: "£79 software offer just became FREE", minsAgo: 4 },
  { id: "a6", text: "Creator Drop: skincare set — 12 spots left", minsAgo: 5 },
  { id: "a7", text: "Birmingham free exhibition verified", minsAgo: 6 },
  { id: "a8", text: "No-card AI trial hit 97% success rate", minsAgo: 8 },
];

export const SIGNALS: FreeSignal[] = [
  {
    id: "sig-coffee-london",
    title: "Free Coffee — First 100",
    summary: "Independent café giving free flat whites to the first 100 customers this morning.",
    category: "eat",
    subcategory: "Drinks",
    location: "Bromley High Street",
    distanceMiles: 0.8,
    freeScore: 94,
    normalValue: 3.8,
    claims: 143,
    watching: 217,
    remaining: 72,
    successRate: 96,
    verifiedMinsAgo: 7,
    requiresCard: false,
    cancelReminder: false,
    verification: "exclusive",
    status: "live",
    activityDelta: 34,
    city: "London",
    workedFor: 1342,
    didntWork: 41,
    updates: [
      { time: "18:32", text: "Member confirmed offer working" },
      { time: "18:21", text: "14 new claims" },
      { time: "18:04", text: "Availability changed — 72 remaining" },
      { time: "17:46", text: "Offer verified" },
    ],
    tags: ["No card", "Near you", "Food"],
  },
  {
    id: "sig-spotify",
    title: "Spotify Premium — 30 Day Trial",
    summary: "Full Premium access for 30 days. Cancel reminder available before billing starts.",
    category: "try",
    subcategory: "Streaming",
    location: "Nationwide",
    freeScore: 91,
    normalValue: 11.99,
    claims: 2481,
    watching: 604,
    successRate: 97,
    verifiedMinsAgo: 11,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 3,
    city: "UK",
    workedFor: 2104,
    didntWork: 68,
    updates: [
      { time: "19:01", text: "51 people already in" },
      { time: "18:58", text: "Signal just dropped" },
      { time: "18:55", text: "Verified by ZeroSpenders" },
    ],
    tags: ["Trial", "Cancel reminder", "Entertainment"],
  },
  {
    id: "sig-family-tickets",
    title: "Free Family Attraction Tickets",
    summary: "Family of four entry to a major attraction. Limited inventory — ending fast.",
    category: "kids",
    subcategory: "Attractions",
    location: "London",
    distanceMiles: 4.3,
    freeScore: 88,
    normalValue: 72,
    claims: 327,
    watching: 327,
    remaining: 18,
    successRate: 91,
    verifiedMinsAgo: 22,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 1.7,
    city: "London",
    workedFor: 289,
    didntWork: 28,
    updates: [
      { time: "17:12", text: "Only 18 left" },
      { time: "16:40", text: "327 watching" },
      { time: "15:05", text: "Community confirmed working" },
    ],
    tags: ["Kids", "Ending soon", "High value"],
  },
  {
    id: "sig-museum",
    title: "Natural History Museum — Free Entry",
    summary: "Permanent collections always free. Timed entry recommended at weekends.",
    category: "go",
    subcategory: "Museums",
    location: "South Kensington",
    distanceMiles: 2.1,
    freeScore: 86,
    normalValue: 0,
    claims: 1206,
    watching: 188,
    successRate: 99,
    verifiedMinsAgo: 4,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "London",
    workedFor: 1180,
    didntWork: 9,
    updates: [
      { time: "19:10", text: "Last verified 4 mins ago" },
      { time: "12:00", text: "Weekend queues expected" },
    ],
    tags: ["Always free", "Family", "Culture"],
  },
  {
    id: "sig-skincare",
    title: "Premium Skincare Sample Set",
    summary: "Brand sample pack by post. No purchase necessary. Limited to UK addresses.",
    category: "get",
    subcategory: "Beauty",
    location: "UK delivery",
    freeScore: 82,
    normalValue: 28,
    claims: 894,
    watching: 412,
    remaining: 210,
    successRate: 88,
    verifiedMinsAgo: 35,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "UK",
    workedFor: 712,
    didntWork: 96,
    updates: [
      { time: "16:20", text: "Community signal upgraded after 40 confirms" },
      { time: "14:02", text: "210 packs remaining" },
    ],
    tags: ["Samples", "Beauty", "No purchase"],
    sponsored: true,
  },
  {
    id: "sig-coding",
    title: "Free Intro to Coding Certificate",
    summary: "Self-paced online course with a free certificate on completion.",
    category: "learn",
    subcategory: "Courses",
    location: "Online",
    freeScore: 79,
    normalValue: 49,
    claims: 1560,
    watching: 290,
    successRate: 94,
    verifiedMinsAgo: 60,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "Online",
    workedFor: 1402,
    didntWork: 88,
    updates: [
      { time: "10:00", text: "Verified working" },
      { time: "09:12", text: "Certificate download confirmed" },
    ],
    tags: ["Courses", "Certificate", "No card"],
  },
  {
    id: "sig-game",
    title: "PC Game Giveaway Weekend",
    summary: "Full game unlock for a limited weekend window. Claim before Monday.",
    category: "play",
    subcategory: "Games",
    location: "Online",
    freeScore: 84,
    normalValue: 24.99,
    claims: 4320,
    watching: 980,
    remaining: 0,
    successRate: 92,
    verifiedMinsAgo: 15,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "ending",
    endsInHours: 36,
    city: "Online",
    workedFor: 3901,
    didntWork: 310,
    updates: [
      { time: "18:00", text: "Still reclaimable" },
      { time: "08:00", text: "Weekend window opened" },
    ],
    tags: ["Games", "Limited time"],
  },
  {
    id: "sig-ai",
    title: "AI Writing Suite — No Card Trial",
    summary: "14-day full access. No credit card required to start.",
    category: "online",
    subcategory: "AI Tools",
    location: "Online",
    freeScore: 90,
    normalValue: 29,
    claims: 1104,
    watching: 501,
    successRate: 95,
    verifiedMinsAgo: 9,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "new",
    droppedMinsAgo: 18,
    city: "Online",
    workedFor: 998,
    didntWork: 42,
    updates: [
      { time: "19:05", text: "No card confirmed" },
      { time: "18:47", text: "Signal detected" },
    ],
    tags: ["AI", "No card", "Tools"],
  },
  {
    id: "sig-yoga",
    title: "Outdoor Yoga — Free Community Class",
    summary: "Saturday morning park class. Mats provided for the first 40 arrivals.",
    category: "go",
    subcategory: "Exercise",
    location: "Hyde Park",
    distanceMiles: 1.4,
    freeScore: 77,
    normalValue: 15,
    claims: 86,
    watching: 64,
    remaining: 40,
    successRate: 93,
    verifiedMinsAgo: 120,
    requiresCard: false,
    cancelReminder: false,
    verification: "community",
    status: "live",
    city: "London",
    workedFor: 71,
    didntWork: 5,
    updates: [
      { time: "Yesterday", text: "Reported by community member" },
    ],
    tags: ["Exercise", "Weekend", "Near you"],
  },
  {
    id: "sig-birthday",
    title: "Birthday Free Dessert",
    summary: "Free dessert with any main on your birthday month. App signup required.",
    category: "eat",
    subcategory: "Birthday",
    location: "Nationwide",
    freeScore: 71,
    normalValue: 6.5,
    claims: 2201,
    watching: 155,
    successRate: 89,
    verifiedMinsAgo: 200,
    requiresCard: false,
    cancelReminder: false,
    verification: "verified",
    status: "live",
    city: "UK",
    workedFor: 1890,
    didntWork: 210,
    updates: [
      { time: "Mon", text: "Verified across 40 locations" },
    ],
    tags: ["Birthday", "Food"],
  },
  {
    id: "sig-kids-softplay",
    title: "Kids Soft Play — Free Taster",
    summary: "One free hour for under-8s this weekend. Book slot online.",
    category: "kids",
    subcategory: "Activities",
    location: "Manchester",
    distanceMiles: 3.2,
    freeScore: 85,
    normalValue: 12,
    claims: 194,
    watching: 122,
    remaining: 55,
    successRate: 90,
    verifiedMinsAgo: 40,
    requiresCard: false,
    cancelReminder: false,
    verification: "exclusive",
    status: "new",
    droppedMinsAgo: 55,
    city: "Manchester",
    workedFor: 160,
    didntWork: 18,
    updates: [
      { time: "17:30", text: "Exclusive business listing" },
      { time: "17:00", text: "Weekend slots opened" },
    ],
    tags: ["Kids", "Weekend", "Exclusive"],
  },
  {
    id: "sig-gym",
    title: "Gym — Free Week Pass",
    summary: "Full club access for 7 days. No contract. Card held but not charged if cancelled.",
    category: "try",
    subcategory: "Gyms",
    location: "Multiple cities",
    freeScore: 76,
    normalValue: 35,
    claims: 670,
    watching: 240,
    successRate: 86,
    verifiedMinsAgo: 80,
    requiresCard: true,
    cancelReminder: true,
    verification: "verified",
    status: "live",
    city: "UK",
    workedFor: 540,
    didntWork: 88,
    updates: [
      { time: "Noon", text: "Cancel reminder enabled" },
    ],
    tags: ["Gym", "Trial", "Cancel reminder"],
  },
];

export const CREATOR_DROPS: CreatorDrop[] = [
  {
    id: "drop-skincare",
    title: "Premium Skincare Set",
    brand: "Lumina Skin",
    retailValue: 85,
    available: 100,
    applied: 47,
    selected: 23,
    closesInHours: 18,
    matchScore: 94,
    requirements: ["Instagram / TikTok", "Beauty audience", "UK", "1,000+ followers"],
    missionType: "TRY & TELL",
    category: "Beauty",
  },
  {
    id: "drop-dinner",
    title: "Free Dinner for Two",
    brand: "Borough Kitchen",
    retailValue: 75,
    available: 12,
    applied: 31,
    selected: 4,
    closesInHours: 48,
    matchScore: 88,
    requirements: ["1 Reel + 3 Stories", "Food audience", "London"],
    missionType: "LOCAL CREATOR MISSION",
    category: "Food",
  },
  {
    id: "drop-energy",
    title: "New Energy Drink Pack",
    brand: "Volt Run",
    retailValue: 18,
    available: 500,
    applied: 126,
    selected: 80,
    closesInHours: 72,
    matchScore: 81,
    requirements: ["Fitness / running interest", "TikTok or Instagram", "UGC welcome"],
    missionType: "TRY & TELL",
    category: "Fitness",
  },
];

export function scoreLabel(score: number): ScoreLabel {
  if (score >= 85) return "EXCEPTIONAL FREEBIE";
  if (score >= 65) return "GOOD SIGNAL";
  return "LOW CONFIDENCE";
}

export function formatGBP(n: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    maximumFractionDigits: n % 1 === 0 ? 0 : 2,
  }).format(n);
}

export function getSignal(id: string) {
  return SIGNALS.find((s) => s.id === id);
}

export function signalsByCategory(category: SignalCategory) {
  return SIGNALS.filter((s) => s.category === category);
}

export function trendingSignals() {
  return [...SIGNALS].sort((a, b) => (b.activityDelta ?? b.claims) - (a.activityDelta ?? a.claims)).slice(0, 5);
}

export function justDroppedSignals() {
  return SIGNALS.filter((s) => s.status === "new" || (s.droppedMinsAgo ?? 999) < 60)
    .sort((a, b) => (a.droppedMinsAgo ?? 999) - (b.droppedMinsAgo ?? 999))
    .slice(0, 5);
}

export function endingSoonSignals() {
  return SIGNALS.filter((s) => s.status === "ending" || (s.remaining !== undefined && s.remaining < 30))
    .sort((a, b) => (a.endsInHours ?? 99) - (b.endsInHours ?? 99))
    .slice(0, 5);
}

export function nearYouSignals() {
  return SIGNALS.filter((s) => s.distanceMiles !== undefined).sort(
    (a, b) => (a.distanceMiles ?? 99) - (b.distanceMiles ?? 99)
  );
}
