import type { EvergreenSource } from "./evergreen-types";

/**
 * UK-first free offers: birthday rewards, trials, samples, libraries, heritage.
 * Prefer official claim URLs + howToClaim so members can verify the deal exists.
 */
export const UK_FREE_SOURCES: EvergreenSource[] = [
  // —— Birthday freebies ——
  {
    title: "Costa Club birthday drink",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.costa.co.uk/costa-club",
    howToClaim:
      "1. Join Costa Club for free in the app or online.\n2. Add your birthday in your profile.\n3. Claim the birthday reward in the app during your birthday period and redeem in store.",
    subcategory: "Birthday",
    normalValue: 4,
    summary: "Costa Club members often get a free birthday drink. Offers change — confirm in the app.",
    category: "EAT",
    sourceName: "Costa Club",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["birthday", "rewards", "coffee"],
  },
  {
    title: "Greggs Rewards birthday freebie",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.greggs.co.uk/rewards",
    howToClaim:
      "1. Download the Greggs app and join Rewards.\n2. Add your date of birth.\n3. Check the app around your birthday for the free item and redeem in store.",
    subcategory: "Birthday",
    normalValue: 3,
    summary: "Greggs Rewards birthday treat for members. Confirm current reward in the app.",
    category: "EAT",
    sourceName: "Greggs Rewards",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["birthday", "rewards"],
  },
  {
    title: "Nando's NandoCard birthday reward",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.nandos.co.uk/nandocard",
    howToClaim:
      "1. Sign up for a free NandoCard online or in the app.\n2. Save your birthday.\n3. Check for birthday rewards and redeem per current NandoCard terms.",
    subcategory: "Birthday",
    normalValue: 8,
    summary: "NandoCard members may get a birthday reward. Terms change — verify in account.",
    category: "EAT",
    sourceName: "Nando's NandoCard",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "rewards"],
  },
  {
    title: "Pret Coffee Subscription birthday / rewards",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.pret.co.uk/en-GB/pret-coffee-subscription",
    howToClaim:
      "1. Open Pret’s official rewards / subscription page.\n2. Check current free trial or birthday promotions.\n3. Cancel any paid plan before the trial ends if you only want free use.",
    subcategory: "Birthday",
    normalValue: 30,
    summary: "Pret often runs coffee subscription trials and member rewards. Card may be required — set a cancel reminder.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Pret",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "coffee"],
  },
  {
    title: "Hotel Chocolat birthday freebie",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.hotelchocolat.com/uk/vip.html",
    howToClaim:
      "1. Join Hotel Chocolat VIP for free.\n2. Add your birthday in your account.\n3. Claim the birthday reward online or in store when it appears.",
    subcategory: "Birthday",
    normalValue: 6,
    summary: "VIP members often get a birthday chocolate treat. Confirm in account.",
    category: "GET",
    sourceName: "Hotel Chocolat VIP",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "rewards"],
  },
  {
    title: "The Body Shop Love Your Body birthday gift",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.thebodyshop.com/en-gb/loyalty",
    howToClaim:
      "1. Join Love Your Body Club online or in store.\n2. Add your birthday.\n3. Redeem the birthday gift in your birthday month per current terms.",
    subcategory: "Birthday",
    normalValue: 10,
    summary: "Loyalty members can claim a birthday gift. Offers change — check the club page.",
    category: "GET",
    sourceName: "The Body Shop",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "beauty"],
  },
  {
    title: "Superdrug Health & Beautycard birthday treat",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.superdrug.com/beautycard",
    howToClaim:
      "1. Sign up for a free Health & Beautycard.\n2. Register your birthday.\n3. Collect the birthday treat in store or online when available.",
    subcategory: "Birthday",
    normalValue: 5,
    summary: "Beautycard birthday rewards for members. Confirm current offer in account.",
    category: "GET",
    sourceName: "Superdrug Beautycard",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "beauty"],
  },
  {
    title: "Boots Advantage Card birthday reward",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.boots.com/advantage-card",
    howToClaim:
      "1. Join Boots Advantage Card for free.\n2. Ensure your birthday is on file.\n3. Check for birthday offers in the app or online and redeem as instructed.",
    subcategory: "Birthday",
    normalValue: 5,
    summary: "Advantage Card members may receive birthday offers. Verify in Boots account.",
    category: "GET",
    sourceName: "Boots Advantage Card",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "rewards"],
  },
  {
    title: "PizzaExpress Club birthday reward",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.pizzaexpress.com/club",
    howToClaim:
      "1. Join PizzaExpress Club online.\n2. Add your birthday.\n3. Redeem birthday rewards in restaurant when they appear in your account.",
    subcategory: "Birthday",
    normalValue: 12,
    summary: "Club members often get birthday dining rewards. Confirm current terms.",
    category: "EAT",
    sourceName: "PizzaExpress Club",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "dining"],
  },
  {
    title: "Krispy Kreme UK birthday doughnut",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.krispykreme.co.uk/rewards",
    howToClaim:
      "1. Join Krispy Kreme Rewards (UK).\n2. Save your birthday.\n3. Claim the birthday doughnut in the app and redeem in store.",
    subcategory: "Birthday",
    normalValue: 3,
    summary: "Rewards members can often claim a free birthday doughnut. Confirm in the app.",
    category: "EAT",
    sourceName: "Krispy Kreme Rewards UK",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["birthday", "rewards"],
  },

  // —— Free trials (UK) ——
  {
    title: "Disney+ free trial (when offered)",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.disneyplus.com/",
    howToClaim:
      "1. Open Disney+ and start signup for the UK.\n2. Check if a free trial is currently offered (not always available).\n3. Add a cancel reminder before the trial ends so you are not charged.",
    subcategory: "Streaming trial",
    normalValue: 8,
    summary: "Disney+ occasionally offers a free trial in the UK. Card usually required.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Disney+",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "streaming"],
  },
  {
    title: "Amazon Prime free trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.amazon.co.uk/prime",
    howToClaim:
      "1. Open Amazon Prime UK signup.\n2. Start the free trial if eligible (new members only).\n3. Cancel before the trial ends via Account → Memberships.",
    subcategory: "Membership trial",
    normalValue: 9,
    summary: "New Amazon Prime members may get a free trial. Card required — cancel before billing.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Amazon Prime UK",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["trial", "amazon"],
  },
  {
    title: "Audible free trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.audible.co.uk/",
    howToClaim:
      "1. Start an Audible UK membership trial on the official site.\n2. Download your included title during the trial.\n3. Cancel before renewal if you do not want to keep paying.",
    subcategory: "Audiobook trial",
    normalValue: 8,
    summary: "Audible often offers a free trial with credits. Card required.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Audible UK",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["trial", "audiobooks"],
  },
  {
    title: "Spotify Premium free trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.spotify.com/uk/premium/",
    howToClaim:
      "1. Open Spotify Premium UK.\n2. Start the free trial if you are eligible.\n3. Cancel before the trial ends in Account → Subscription.",
    subcategory: "Music trial",
    normalValue: 11,
    summary: "Eligible users can try Spotify Premium free. Card usually required.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Spotify",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["trial", "music"],
  },
  {
    title: "Apple TV+ free trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://tv.apple.com/",
    howToClaim:
      "1. Open Apple TV+ and start a free trial via your Apple ID.\n2. Confirm the trial length shown at signup.\n3. Cancel in Settings → Subscriptions before it renews.",
    subcategory: "Streaming trial",
    normalValue: 9,
    summary: "Apple TV+ free trial for eligible Apple IDs. Cancel before billing.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Apple TV+",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["trial", "streaming"],
  },
  {
    title: "HelloFresh free box / trial credit",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.hellofresh.co.uk/",
    howToClaim:
      "1. Open HelloFresh UK and check current new-customer free or heavily discounted boxes.\n2. Complete signup (card usually required).\n3. Skip or cancel boxes before the next delivery if you only wanted the intro offer.",
    subcategory: "Meal kit trial",
    normalValue: 35,
    summary: "New customers often get free or discounted first boxes. Card required.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "HelloFresh UK",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "food"],
  },
  {
    title: "Headspace free trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.headspace.com/",
    howToClaim:
      "1. Sign up on Headspace.\n2. Start the free trial of Headspace Plus if offered.\n3. Cancel in account settings before the trial ends.",
    subcategory: "Wellness trial",
    normalValue: 10,
    summary: "Headspace often offers a free trial of premium content.",
    category: "TRY",
    requiresCard: true,
    cancelReminder: true,
    sourceName: "Headspace",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "wellness"],
  },
  {
    title: "PureGym free day pass / trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.puregym.com/",
    howToClaim:
      "1. Open PureGym and search for a gym near you.\n2. Look for free day pass / trial offers on the club page.\n3. Book online and bring photo ID if required.",
    subcategory: "Gym trial",
    normalValue: 25,
    summary: "Many PureGym clubs offer free day passes. Availability varies by club.",
    category: "TRY",
    sourceName: "PureGym",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "gym"],
  },
  {
    title: "The Gym Group free trial workout",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.thegymgroup.com/",
    howToClaim:
      "1. Visit The Gym Group site and pick a local gym.\n2. Book a free trial workout online.\n3. Attend with ID; cancel any membership offer you do not want.",
    subcategory: "Gym trial",
    normalValue: 25,
    summary: "Free trial workouts at participating Gym Group clubs.",
    category: "TRY",
    sourceName: "The Gym Group",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["trial", "gym"],
  },

  // —— Free samples / GET ——
  {
    title: "Free product samples — BrandAlley",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.brandalley.co.uk/",
    howToClaim:
      "1. Create a free BrandAlley account.\n2. Check promotions / sample offers.\n3. Claim while stock lasts; postage rules vary.",
    subcategory: "Samples",
    normalValue: 15,
    summary: "Flash sales site that sometimes lists free sample campaigns. Confirm each offer.",
    category: "GET",
    sourceName: "BrandAlley",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["samples", "beauty"],
  },
  {
    title: "IPSOS i-Say surveys — free rewards",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.i-say.com/",
    howToClaim:
      "1. Register on Ipsos i-Say.\n2. Complete surveys for points.\n3. Redeem points for vouchers / rewards per their catalogue.",
    subcategory: "Surveys",
    normalValue: 5,
    summary: "Free survey panel that pays in vouchers. Not a product sample — time for rewards.",
    category: "GET",
    sourceName: "Ipsos i-Say",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["surveys", "rewards"],
  },
  {
    title: "YouGov surveys — free vouchers",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://yougov.co.uk/",
    howToClaim:
      "1. Join YouGov for free.\n2. Answer surveys when invited.\n3. Cash out points for vouchers when you reach the threshold.",
    subcategory: "Surveys",
    normalValue: 5,
    summary: "Free opinion surveys that convert points into vouchers.",
    category: "GET",
    sourceName: "YouGov",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["surveys", "rewards"],
  },

  // —— Heritage / GO ——
  {
    title: "English Heritage — free for members / open days",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.english-heritage.org.uk/",
    howToClaim:
      "1. Open English Heritage and check free open days or membership offers.\n2. Book timed tickets when required.\n3. Bring confirmation email / membership card on the day.",
    subcategory: "Heritage",
    normalValue: 15,
    summary: "Some English Heritage sites run free open days; members visit free. Confirm per site.",
    category: "GO",
    sourceName: "English Heritage",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["heritage", "days-out"],
  },
  {
    title: "National Trust — free entry days / membership trial",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.nationaltrust.org.uk/",
    howToClaim:
      "1. Check National Trust for free entry events or gift membership trials.\n2. Book where booking is required.\n3. Bring booking reference or membership card.",
    subcategory: "Heritage",
    normalValue: 20,
    summary: "National Trust properties are free to members; occasional free community days.",
    category: "GO",
    sourceName: "National Trust",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["heritage", "days-out"],
  },
  {
    title: "CADW — free entry days Wales",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://cadw.gov.wales/",
    howToClaim:
      "1. Visit Cadw’s events / visit pages.\n2. Look for free entry days at castles and historic sites.\n3. Book if required and bring confirmation.",
    subcategory: "Heritage",
    normalValue: 12,
    summary: "Welsh historic sites sometimes offer free entry days. Confirm on Cadw.",
    category: "GO",
    sourceName: "Cadw",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["heritage", "wales"],
  },
  {
    title: "Historic Environment Scotland — free Sundays (selected)",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.historicenvironment.scot/",
    howToClaim:
      "1. Check Historic Environment Scotland for free access programmes.\n2. Confirm which properties and dates are free.\n3. Arrive with any required booking.",
    subcategory: "Heritage",
    normalValue: 12,
    summary: "Selected HES properties have free access windows — confirm current scheme.",
    category: "GO",
    sourceName: "Historic Environment Scotland",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["heritage", "scotland"],
  },

  // —— Learn / libraries ——
  {
    title: "BorrowBox — free ebooks via your library card",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.borrowbox.com/",
    howToClaim:
      "1. Get a free card from your local UK public library.\n2. Download BorrowBox and sign in with your library number.\n3. Borrow ebooks and audiobooks at £0.",
    subcategory: "Library",
    normalValue: 10,
    summary: "Free digital loans through participating UK public libraries.",
    category: "LEARN",
    sourceName: "BorrowBox",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["library", "ebooks"],
  },
  {
    title: "Libby / OverDrive — free library ebooks",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.overdrive.com/",
    howToClaim:
      "1. Join your local library for free.\n2. Open Libby and add your library card.\n3. Borrow ebooks and magazines for free.",
    subcategory: "Library",
    normalValue: 10,
    summary: "Free digital borrowing via many UK library services.",
    category: "LEARN",
    sourceName: "Libby / OverDrive",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["library", "ebooks"],
  },
  {
    title: "Open University OpenLearn — free courses",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.open.edu/openlearn/",
    howToClaim:
      "1. Open OpenLearn.\n2. Create a free account.\n3. Enrol on any free course and download statements of participation.",
    subcategory: "Courses",
    normalValue: 0,
    summary: "Hundreds of free online courses from The Open University.",
    category: "LEARN",
    sourceName: "OpenLearn",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["courses", "online"],
  },
  {
    title: "BBC Bitesize — free learning",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.bbc.co.uk/bitesize",
    howToClaim:
      "1. Open BBC Bitesize.\n2. Pick a subject and level.\n3. Study for free — no payment required.",
    subcategory: "Study",
    normalValue: 0,
    summary: "Free revision and learning resources from the BBC.",
    category: "LEARN",
    sourceName: "BBC Bitesize",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["kids", "study"],
  },
  {
    title: "FutureLearn free courses (audit)",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.futurelearn.com/",
    howToClaim:
      "1. Create a FutureLearn account.\n2. Enrol on a course that offers free access.\n3. Complete within the free window; upgrades are optional.",
    subcategory: "Courses",
    normalValue: 0,
    summary: "Many FutureLearn courses can be audited free for a limited time.",
    category: "LEARN",
    sourceName: "FutureLearn",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["courses", "online"],
  },

  // —— Kids ——
  {
    title: "BookTrust — free books for children programmes",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.booktrust.org.uk/",
    howToClaim:
      "1. Visit BookTrust and check current free book programmes (e.g. Bookstart).\n2. See if your child is eligible via health visitor / library / school.\n3. Collect books through the listed partners.",
    subcategory: "Kids books",
    normalValue: 20,
    summary: "BookTrust runs free book gifting programmes for UK children.",
    category: "KIDS",
    sourceName: "BookTrust",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["kids", "books"],
  },
  {
    title: "Local library — free children's storytime",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.gov.uk/local-library-services",
    howToClaim:
      "1. Find your local library via GOV.UK.\n2. Check the events calendar for free storytime / rhyme time.\n3. Turn up or book if the library asks you to.",
    subcategory: "Kids events",
    normalValue: 8,
    summary: "Most UK public libraries run free storytime sessions for under-5s.",
    category: "KIDS",
    sourceName: "UK public libraries",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["kids", "library"],
  },

  // —— Play / online ——
  {
    title: "BBC Sounds — free podcasts & radio",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.bbc.co.uk/sounds",
    howToClaim:
      "1. Open BBC Sounds in browser or app.\n2. Sign in with a free BBC account if prompted.\n3. Stream podcasts and radio at £0.",
    subcategory: "Audio",
    normalValue: 0,
    summary: "Free UK radio, music mixes and podcasts from the BBC.",
    category: "PLAY",
    sourceName: "BBC Sounds",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["audio", "online"],
  },
  {
    title: "BBC iPlayer — free TV (UK licence)",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.bbc.co.uk/iplayer",
    howToClaim:
      "1. Open BBC iPlayer.\n2. Sign in with a free BBC account.\n3. Stream if you are covered by a UK TV Licence where required.",
    subcategory: "Streaming",
    normalValue: 0,
    summary: "Free catch-up TV for licence-fee payers in the UK.",
    category: "ONLINE",
    sourceName: "BBC iPlayer",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["streaming", "tv"],
  },
  {
    title: "Channel 4 — free streaming",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.channel4.com/",
    howToClaim:
      "1. Open Channel 4.\n2. Create a free account.\n3. Watch ad-supported programmes for free in the UK.",
    subcategory: "Streaming",
    normalValue: 0,
    summary: "Free ad-supported on-demand TV from Channel 4.",
    category: "ONLINE",
    sourceName: "Channel 4",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["streaming", "tv"],
  },
  {
    title: "ITVX — free streaming tier",
    city: "Nationwide",
    country: "GB",
    claimUrl: "https://www.itv.com/",
    howToClaim:
      "1. Open ITVX.\n2. Register for a free account.\n3. Watch the free ad-supported catalogue (Premium is optional).",
    subcategory: "Streaming",
    normalValue: 0,
    summary: "Free ITVX tier with ads — no subscription required for core catalogue.",
    category: "ONLINE",
    sourceName: "ITVX",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["streaming", "tv"],
  },

  // —— More museums with claim paths ——
  {
    title: "Imperial War Museum Duxford — free outdoor areas check",
    city: "Duxford",
    country: "GB",
    claimUrl: "https://www.iwm.org.uk/visits/iwm-duxford",
    claimPhone: "01223 835 000",
    howToClaim:
      "1. Check IWM Duxford’s visit page for current admission policy.\n2. Book tickets if charged; ask about any free community days.\n3. Call the number if you need access advice.",
    subcategory: "Museum",
    normalValue: 22,
    summary: "Confirm free/paid admission on the official IWM page before travel.",
    category: "GO",
    sourceName: "Imperial War Museums",
    sourceType: "OFFICIAL",
    verification: "COMMUNITY",
    tags: ["museum"],
  },
  {
    title: "V&A Dundee — check free exhibitions",
    city: "Dundee",
    country: "GB",
    claimUrl: "https://www.vam.ac.uk/dundee",
    howToClaim:
      "1. Open the V&A Dundee visit page.\n2. See which galleries are free vs ticketed.\n3. Book free timed entry if required.",
    subcategory: "Museum",
    normalValue: 12,
    summary: "Design museum — permanent displays are often free; special shows may charge.",
    category: "GO",
    sourceName: "V&A Dundee",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["museum", "gallery"],
  },
  {
    title: "Design Museum London — free permanent collection",
    city: "London",
    country: "GB",
    claimUrl: "https://designmuseum.org/",
    howToClaim:
      "1. Open the Design Museum website.\n2. Confirm free permanent collection access.\n3. Book or walk in as instructed for the day.",
    subcategory: "Museum",
    normalValue: 15,
    summary: "Permanent collection is typically free; temporary exhibitions may charge.",
    category: "GO",
    sourceName: "Design Museum",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["museum", "design"],
  },
  {
    title: "Saatchi Gallery — free exhibitions (check calendar)",
    city: "London",
    country: "GB",
    claimUrl: "https://www.saatchigallery.com/",
    howToClaim:
      "1. Check Saatchi Gallery’s what’s on page.\n2. Confirm which shows are free.\n3. Visit during free opening hours.",
    subcategory: "Gallery",
    normalValue: 12,
    summary: "Many Saatchi exhibitions are free entry — confirm each show.",
    category: "GO",
    sourceName: "Saatchi Gallery",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["gallery"],
  },
  {
    title: "Southbank Centre — free foyer events",
    city: "London",
    country: "GB",
    claimUrl: "https://www.southbankcentre.co.uk/",
    howToClaim:
      "1. Open Southbank Centre what’s on.\n2. Filter for free events.\n3. Turn up or book free tickets when listed.",
    subcategory: "Arts",
    normalValue: 15,
    summary: "Regular free music, talks and foyer events on the South Bank.",
    category: "GO",
    sourceName: "Southbank Centre",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["arts", "events"],
  },
  {
    title: "Barbican — free foyer & library",
    city: "London",
    country: "GB",
    claimUrl: "https://www.barbican.org.uk/",
    howToClaim:
      "1. Check Barbican visit / free events pages.\n2. Access the free public library and foyer areas.\n3. Book free events when reservation is needed.",
    subcategory: "Arts",
    normalValue: 10,
    summary: "Public foyers and library access are free; ticketed shows are separate.",
    category: "GO",
    sourceName: "Barbican",
    sourceType: "OFFICIAL",
    verification: "VERIFIED",
    tags: ["arts", "library"],
  },
];
